# Generated by Django 4.0.2 on 2022-03-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_location_locationname_event_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventDescription',
            field=models.CharField(default='', max_length=300),
        ),
    ]
