# Generated by Django 4.0.2 on 2022-03-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='EventID',
            new_name='EventId',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='UserID',
            new_name='UserId',
        ),
    ]
