# Generated by Django 4.0.2 on 2022-02-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='LoginCls',
        ),
    ]
