# Generated by Django 4.0.2 on 2022-03-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_login_logincls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginCls',
        ),
    ]
