# Generated by Django 4.0.2 on 2022-03-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_delete_logincls'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCls',
            fields=[
                ('Email', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
