# Generated by Django 4.0.2 on 2022-03-03 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginCls',
        ),
    ]
