const events = [
  {
    eventid: 1,
    eventname: "Lyrical Melody",
    eventdescription: "Location hosted at Serendipity Martini Bar",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "10/3/2022",
    starttime: "9:00 PM",
    endtime: "2:00 AM",
  },
  {
    eventid: 2,
    eventname: "SmokePurp",
    eventdescription: "Location hosted at Kalao",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "11/4/2022",
    starttime: "10:00 PM",
    endtime: "1:00 AM",
  },
  {
    eventid: 3,
    eventname: "Tony Martinez",
    eventdescription: "Location hosted at KillRoys sport club",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "11/4/2022",
    starttime: "10:00 PM",
    endtime: "1:00 AM",
  },
  {
    eventid: 4,
    eventname: "Tony Martinez",
    eventdescription: "Location hosted at Labuna Mexican Grill",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "12/3/2022",
    starttime: "5:00 PM",
    endtime: "8:00 PM",
  },
  {
    eventid: 5,
    eventname: "John Walker",
    eventdescription: "Location hosted at Kalao",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "13/3/2022",
    starttime: "10:00 PM",
    endtime: "1:00 AM",
  },
  {
    eventid: 6,
    eventname: "Philip Miles",
    eventdescription: "Location hosted at KillRoys sport club",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "11/4/2022",
    starttime: "9:00 AM",
    endtime: "12:00 PM",
  },
  {
    eventid: 7,
    eventname: "Jhonty Beats",
    eventdescription: "Location hosted at Serendipity Martini Bar",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "20/3/2022",
    starttime: "9:00 AM",
    endtime: "12:00 PM",
  },
  {
    eventid: 8,
    eventname: "Jhonty Beats",
    eventdescription: "Location hosted at Serendipity Martini Bar",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "30/3/2022",
    starttime: "9:00 AM",
    endtime: "12:00 PM",
  },
  {
    eventid: 9,
    eventname: "Philip Miles",
    eventdescription: "Location hosted at KillRoys sport club",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "13/3/2022",
    starttime: "9:00 PM",
    endtime: "2:00 AM",
  },
  {
    eventid: 10,
    eventname: "Philip Miles",
    eventdescription: "Location hosted at Labuna Mexican Grill",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "10/3/2022",
    starttime: "10:00 PM",
    endtime: "1:00 AM",
  },
  {
    eventid: 11,
    eventname: "Mono Action",
    eventdescription: "Location hosted at SimonSkjot Halll",
    eventgenre: "Acting",
    eventtype: "Theater",
    date: "11/4/2022",
    starttime: "9:00 PM",
    endtime: "2:00 AM",
  },
  {
    eventid: 12,
    eventname: "Hip Hop",
    eventdescription: "Location hosted at KillRoys sport club",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "7/4/2022",
    starttime: "10:00 PM",
    endtime: "1:00 AM",
  },
  {
    eventid: 13,
    eventname: "Boogey Man",
    eventdescription: "Location hosted at Serendipity Martini Bar",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "11/4/2022",
    starttime: "5:00 PM",
    endtime: "8:00 PM",
  },
  {
    eventid: 14,
    eventname: "Mike P",
    eventdescription: "Location hosted at Labuna Mexican Grill",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "18/3/2022",
    starttime: "9:00 AM",
    endtime: "12:00 PM",
  },
  {
    eventid: 15,
    eventname: "Mike P",
    eventdescription: "Location hosted at Kalao",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "11/4/2022",
    starttime: "9:00 PM",
    endtime: "2:00 AM",
  },
  {
    eventid: 16,
    eventname: "Sydney Adams",
    eventdescription: "Location hosted at SimonSkjot Halll",
    eventgenre: "Acting",
    eventtype: "Theater",
    date: "11/4/2022",
    starttime: "5:00 PM",
    endtime: "8:00 PM",
  },
  {
    eventid: 17,
    eventname: "Blues Whales Festival",
    eventdescription: "Location hosted at Labuna Mexican Grill",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "12/4/2022",
    starttime: "9:00 PM",
    endtime: "2:00 AM",
  },
  {
    eventid: 18,
    eventname: "Beatles Live",
    eventdescription: "Location hosted at SimonSkjot Halll",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "8/4/2022",
    starttime: "9:00 AM",
    endtime: "12:00 PM",
  },
  {
    eventid: 19,
    eventname: "Sydney Adams",
    eventdescription: "Location hosted at Labuna Mexican Grill",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "15/3/2022",
    starttime: "9:00 AM",
    endtime: "12:00 PM",
  },
  {
    eventid: 20,
    eventname: "Drip Dunns",
    eventdescription: "Location hosted at Labuna Mexican Grill",
    eventgenre: "Music",
    eventtype: "Concert",
    date: "20/4/2022",
    starttime: "5:00 PM",
    endtime: "8:00 PM",
  },
];

export default events;