# Generated by Django 4.0.2 on 2022-03-05 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0003_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationId', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('LocationName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventId', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=50)),
                ('EventGenre', models.CharField(max_length=50)),
                ('EventType', models.CharField(max_length=50)),
                ('EventDate', models.DateField()),
                ('EventStartTime', models.TimeField(max_length=50)),
                ('EventEndTime', models.TimeField(max_length=50)),
                ('Performer', models.CharField(max_length=50)),
                ('MaxNoOfSeats', models.IntegerField(max_length=50)),
                ('SeatsAvailable', models.IntegerField(default='', max_length=10)),
                ('Price', models.IntegerField(max_length=3)),
                ('HostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.host')),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.location')),
            ],
        ),
    ]
