# Generated by Django 4.0.2 on 2022-03-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='MaxNoOfSeats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='SeatsAvailable',
            field=models.IntegerField(),
        ),
    ]
