# Generated by Django 4.0.2 on 2022-03-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_eventid_alter_event_maxnoofseats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='LocationId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
