# Generated by Django 4.0.2 on 2022-03-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_location_locationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='LocationName',
        ),
        migrations.AddField(
            model_name='event',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='EventDescription',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='City',
            field=models.CharField(default='Bloomington', max_length=64),
        ),
    ]
