# Generated by Django 4.0.2 on 2022-03-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_eventdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ZipCode',
            field=models.CharField(default='47401', max_length=5),
        ),
        migrations.AddField(
            model_name='location',
            name='State',
            field=models.CharField(default='IN', max_length=50),
        ),
    ]
