# Generated by Django 4.0.2 on 2022-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_eventid_bookings_eventid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ImageUrl',
            field=models.URLField(default='', max_length=500),
        ),
    ]
