# Generated by Django 4.0.3 on 2022-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_bookmarks_bookmarkstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='BookingStatus',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
