# Generated by Django 4.0.3 on 2022-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_bookings_bookingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventStatus',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
