# Generated by Django 4.0.3 on 2022-04-25 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_host_password_alter_host_verificationcode_and_more'),
        ('event', '0013_event_eventstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReviews',
            fields=[
                ('ReviewId', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user')),
                ('EventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
