# Generated by Django 4.0.3 on 2022-04-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='CodeCreationTime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='host',
            name='VerificationCode',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='CodeCreationTime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='VerificationCode',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
