# Generated by Django 4.0.3 on 2022-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_host_codecreationtime_host_verificationcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=150),
        ),
    ]
