# Generated by Django 4.0.3 on 2022-04-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='Password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='host',
            name='VerificationCode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='VerificationCode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
